### ISSUE TITLE
[Meta]  CSS Nesting

### ISSUE THREAD

**Issue by black7375** [mincho-js/mincho#45]
### Description

Suggestions for better nesting and referencing.

### Related RFC

https://github.com/mincho-js/working-group/blob/main/text/001-css-nesting.md

### Task or issue list

- [x] 1. Simple Attribute Selectors
  - [x] #14
- [x] 2. Nested Properties
  - [x] #18
  - [x] #23
- [x] 3. Property based condition
  - [x] #20
  - [x] #22
- [x] 4. Nested Selectors
  - [x] #24
  - [x] #26
- [x] 5. Nested At-Rules
  - [x] #25
  - [x] #26
- [x] 6. Property Reference (WIP) #46
  - [x] #47
- [x] #50

### Additional context

Others
- #21
